/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as TasksCompletedRouteImport } from './routes/tasks.completed'
import { Route as TasksCalendarRouteImport } from './routes/tasks.calendar'
import { Route as DashboardWeekRouteImport } from './routes/dashboard.week'
import { Route as DashboardMonthRouteImport } from './routes/dashboard.month'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authForgotPasswordIndexRouteImport } from './routes/(auth)/forgot-password.index'
import { Route as authForgotPasswordVerifyRouteImport } from './routes/(auth)/forgot-password.verify'
import { Route as authForgotPasswordResetRouteImport } from './routes/(auth)/forgot-password.reset'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const TasksCompletedRoute = TasksCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => TasksRoute,
} as any)
const TasksCalendarRoute = TasksCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TasksRoute,
} as any)
const DashboardWeekRoute = DashboardWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMonthRoute = DashboardMonthRouteImport.update({
  id: '/month',
  path: '/month',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordIndexRoute = authForgotPasswordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authForgotPasswordRoute,
} as any)
const authForgotPasswordVerifyRoute =
  authForgotPasswordVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => authForgotPasswordRoute,
  } as any)
const authForgotPasswordResetRoute = authForgotPasswordResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => authForgotPasswordRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/month': typeof DashboardMonthRoute
  '/dashboard/week': typeof DashboardWeekRoute
  '/tasks/calendar': typeof TasksCalendarRoute
  '/tasks/completed': typeof TasksCompletedRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/forgot-password/reset': typeof authForgotPasswordResetRoute
  '/forgot-password/verify': typeof authForgotPasswordVerifyRoute
  '/forgot-password/': typeof authForgotPasswordIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/month': typeof DashboardMonthRoute
  '/dashboard/week': typeof DashboardWeekRoute
  '/tasks/calendar': typeof TasksCalendarRoute
  '/tasks/completed': typeof TasksCompletedRoute
  '/dashboard': typeof DashboardIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/forgot-password/reset': typeof authForgotPasswordResetRoute
  '/forgot-password/verify': typeof authForgotPasswordVerifyRoute
  '/forgot-password': typeof authForgotPasswordIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/month': typeof DashboardMonthRoute
  '/dashboard/week': typeof DashboardWeekRoute
  '/tasks/calendar': typeof TasksCalendarRoute
  '/tasks/completed': typeof TasksCompletedRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/(auth)/forgot-password/reset': typeof authForgotPasswordResetRoute
  '/(auth)/forgot-password/verify': typeof authForgotPasswordVerifyRoute
  '/(auth)/forgot-password/': typeof authForgotPasswordIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/notes'
    | '/settings'
    | '/tasks'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/calendar'
    | '/dashboard/month'
    | '/dashboard/week'
    | '/tasks/calendar'
    | '/tasks/completed'
    | '/dashboard/'
    | '/tasks/'
    | '/forgot-password/reset'
    | '/forgot-password/verify'
    | '/forgot-password/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/notes'
    | '/settings'
    | '/login'
    | '/signup'
    | '/dashboard/calendar'
    | '/dashboard/month'
    | '/dashboard/week'
    | '/tasks/calendar'
    | '/tasks/completed'
    | '/dashboard'
    | '/tasks'
    | '/forgot-password/reset'
    | '/forgot-password/verify'
    | '/forgot-password'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dashboard'
    | '/notes'
    | '/settings'
    | '/tasks'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/dashboard/calendar'
    | '/dashboard/month'
    | '/dashboard/week'
    | '/tasks/calendar'
    | '/tasks/completed'
    | '/dashboard/'
    | '/tasks/'
    | '/(auth)/forgot-password/reset'
    | '/(auth)/forgot-password/verify'
    | '/(auth)/forgot-password/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  NotesRoute: typeof NotesRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/tasks/completed': {
      id: '/tasks/completed'
      path: '/completed'
      fullPath: '/tasks/completed'
      preLoaderRoute: typeof TasksCompletedRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/calendar': {
      id: '/tasks/calendar'
      path: '/calendar'
      fullPath: '/tasks/calendar'
      preLoaderRoute: typeof TasksCalendarRouteImport
      parentRoute: typeof TasksRoute
    }
    '/dashboard/week': {
      id: '/dashboard/week'
      path: '/week'
      fullPath: '/dashboard/week'
      preLoaderRoute: typeof DashboardWeekRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/month': {
      id: '/dashboard/month'
      path: '/month'
      fullPath: '/dashboard/month'
      preLoaderRoute: typeof DashboardMonthRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password/': {
      id: '/(auth)/forgot-password/'
      path: '/'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof authForgotPasswordIndexRouteImport
      parentRoute: typeof authForgotPasswordRoute
    }
    '/(auth)/forgot-password/verify': {
      id: '/(auth)/forgot-password/verify'
      path: '/verify'
      fullPath: '/forgot-password/verify'
      preLoaderRoute: typeof authForgotPasswordVerifyRouteImport
      parentRoute: typeof authForgotPasswordRoute
    }
    '/(auth)/forgot-password/reset': {
      id: '/(auth)/forgot-password/reset'
      path: '/reset'
      fullPath: '/forgot-password/reset'
      preLoaderRoute: typeof authForgotPasswordResetRouteImport
      parentRoute: typeof authForgotPasswordRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardMonthRoute: typeof DashboardMonthRoute
  DashboardWeekRoute: typeof DashboardWeekRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardMonthRoute: DashboardMonthRoute,
  DashboardWeekRoute: DashboardWeekRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface TasksRouteChildren {
  TasksCalendarRoute: typeof TasksCalendarRoute
  TasksCompletedRoute: typeof TasksCompletedRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksCalendarRoute: TasksCalendarRoute,
  TasksCompletedRoute: TasksCompletedRoute,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

interface authForgotPasswordRouteChildren {
  authForgotPasswordResetRoute: typeof authForgotPasswordResetRoute
  authForgotPasswordVerifyRoute: typeof authForgotPasswordVerifyRoute
  authForgotPasswordIndexRoute: typeof authForgotPasswordIndexRoute
}

const authForgotPasswordRouteChildren: authForgotPasswordRouteChildren = {
  authForgotPasswordResetRoute: authForgotPasswordResetRoute,
  authForgotPasswordVerifyRoute: authForgotPasswordVerifyRoute,
  authForgotPasswordIndexRoute: authForgotPasswordIndexRoute,
}

const authForgotPasswordRouteWithChildren =
  authForgotPasswordRoute._addFileChildren(authForgotPasswordRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  DashboardRoute: DashboardRouteWithChildren,
  NotesRoute: NotesRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
