/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksCompletedRouteImport } from './routes/tasks.completed'
import { Route as TasksCalendarRouteImport } from './routes/tasks.calendar'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const TasksCompletedRoute = TasksCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => TasksRoute,
} as any)
const TasksCalendarRoute = TasksCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TasksRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/tasks/calendar': typeof TasksCalendarRoute
  '/tasks/completed': typeof TasksCompletedRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/tasks/calendar': typeof TasksCalendarRoute
  '/tasks/completed': typeof TasksCompletedRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/tasks/calendar': typeof TasksCalendarRoute
  '/tasks/completed': typeof TasksCompletedRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/notes'
    | '/settings'
    | '/tasks'
    | '/login'
    | '/signup'
    | '/tasks/calendar'
    | '/tasks/completed'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/dashboard'
    | '/notes'
    | '/settings'
    | '/login'
    | '/signup'
    | '/tasks/calendar'
    | '/tasks/completed'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dashboard'
    | '/notes'
    | '/settings'
    | '/tasks'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/tasks/calendar'
    | '/tasks/completed'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  DashboardRoute: typeof DashboardRoute
  NotesRoute: typeof NotesRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/completed': {
      id: '/tasks/completed'
      path: '/completed'
      fullPath: '/tasks/completed'
      preLoaderRoute: typeof TasksCompletedRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/calendar': {
      id: '/tasks/calendar'
      path: '/calendar'
      fullPath: '/tasks/calendar'
      preLoaderRoute: typeof TasksCalendarRouteImport
      parentRoute: typeof TasksRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TasksRouteChildren {
  TasksCalendarRoute: typeof TasksCalendarRoute
  TasksCompletedRoute: typeof TasksCompletedRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksCalendarRoute: TasksCalendarRoute,
  TasksCompletedRoute: TasksCompletedRoute,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  DashboardRoute: DashboardRoute,
  NotesRoute: NotesRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
